version: '3.9'
services:
  todo-app:
    build: ./
    ports:
      -8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=testpassword
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=testpassword
    ports:
      - 5432:5432
