services:
  todo-app:
    build: ./
    command: ["sh", "-c", "./wait-for-postgres.sh db ./todo-app"]
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      - DB_PASSWORD=testpassword
    networks:
      - backend

  db:
    restart: always
    image: postgres:latest
    container_name: postgres_db
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=testpassword
    ports:
      - 5432:5432
    networks:
      - backend
  
  redis:
    restart: always
    image: redis:latest
    container_name: redis_server
    ports:
      - 6379:6379
    volumes:
      - ./.database/redis/data:/data
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

networks:
  backend: